# Generated by Django 2.2.2 on 2019-07-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thours', models.IntegerField(default=0)),
                ('tminutes', models.IntegerField(default=0)),
                ('tseconds', models.IntegerField(default=0)),
                ('bhours', models.IntegerField(default=3)),
                ('bminutes', models.IntegerField(default=0)),
                ('bseconds', models.IntegerField(default=0)),
                ('hours', models.IntegerField(default=3)),
                ('minutes', models.IntegerField(default=0)),
                ('seconds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('off', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questionpool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('ans', models.CharField(max_length=100)),
                ('anscopy', models.CharField(default=None, max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('score3', models.IntegerField(default=0)),
                ('att', models.BooleanField(default=False)),
            ],
        ),
    ]
